package com.biology.humancell3d;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.webkit.WebResourceRequest;
import android.webkit.WebView;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.BridgeWebViewClient;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Native Android intent client for Google Scene Viewer & Chrome browser
        this.bridge.getWebView().setWebViewClient(new BridgeWebViewClient(this.bridge) {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
                Uri reqUri = request.getUrl();
                String urlStr = reqUri.toString();

                // Route Google Scene Viewer / AR requests directly to Chrome system browser
                if (urlStr.contains("arvr.google.com")) {
                    try {
                        Intent intent = new Intent(Intent.ACTION_VIEW, reqUri);
                        intent.setPackage("com.android.chrome");
                        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                        startActivity(intent);
                        return true;
                    } catch (Exception e) {
                        try {
                            Intent intent = new Intent(Intent.ACTION_VIEW, reqUri);
                            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                            startActivity(intent);
                            return true;
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                }

                // Handle intent:// URIs generated by Google model-viewer or Scene Viewer
                if (urlStr.startsWith("intent://")) {
                    try {
                        Intent intent = Intent.parseUri(urlStr, Intent.URI_INTENT_SCHEME);
                        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                        startActivity(intent);
                        return true;
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

                return super.shouldOverrideUrlLoading(view, request);
            }
        });
    }
}

