package com.biology.humancell3d;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.webkit.WebResourceRequest;
import android.webkit.WebView;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.BridgeWebViewClient;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Native Android intent client for Google Scene Viewer & Model Viewer
        this.bridge.getWebView().setWebViewClient(new BridgeWebViewClient(this.bridge) {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
                Uri reqUri = request.getUrl();
                String urlStr = reqUri.toString();

                // Handle intent:// URIs generated by Google model-viewer
                if (urlStr.startsWith("intent://")) {
                    try {
                        Intent intent = Intent.parseUri(urlStr, Intent.URI_INTENT_SCHEME);
                        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                        startActivity(intent);
                        return true;
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

                return super.shouldOverrideUrlLoading(view, request);
            }
        });
    }
}
